version: '3'
services:
  server:
    build: ./back
    tty: true
    volumes:
      - ./back:/go/src/work 
    ports:                      # 追加
      - 3000:3000               # 追加
    command: go run server.go   # 追加
